appvia/appvia-hub

app/controllers/admin/integrations_controller.rb, app/helpers/resources_helper.rb, app/models/project.rb, app/services/resource_types_service.rb, app/views/activity/_stream.html.erb, app/views/admin/integrations/_group.html.erb, app/views/projects/_resources.html.erb, app/views/projects/show.html.erb, app/views/resources/_list-item.html.erb
Part of #105
- Move the resources and activity columns into separate tabs (until we have a better structure for drilling down into details from an overview page).
- Display resources grouped by resource type.
- More compact layout for each resource list item.
=> Revamped layout for the Space page

app/controllers/concerns/error_handlers.rb, app/controllers/projects_controller.rb, app/controllers/resources_controller.rb, app/helpers/application_helper.rb, app/helpers/integrations_helper.rb, app/models/project.rb, app/services/resource_types_service.rb, app/views/admin/integrations/_card.html.erb, app/views/admin/integrations/_form.html.erb, app/views/projects/_resources.html.erb, app/views/projects/show.html.erb, app/views/resources/_form.html.erb, app/views/resources/new.html.erb, app/webpack/packs/application.js.erb, app/webpack/stylesheets/application.scss, config/routes.rb, db/migrate/20190424123818_add_index_for_integrations_provider_id.rb, db/schema.rb, package.json, spec/requests/projects_spec.rb, spec/requests/resources_spec.rb, spec/routing/resources_routing_spec.rb, yarn.lock
Part of #105
This will gracefully handle cases where integrations are not available for a particular resource type.
=> Ability to provision individual resources from the space page

app/lib/json_schema_helpers.rb, app/models/integration.rb, app/views/admin/integrations/_card.html.erb, app/views/admin/integrations/_form.html.erb, app/views/application/forms/_json_schema_fields.html.erb, app/workers/resources/request_create_worker.rb, config/providers.yml, spec/integration/resources/code_repos/git_hub_code_repos_integration_spec.rb, spec/models/integration_spec.rb, spec/support/mocked_integration_helper.rb
=> Option to apply best practices to GitHub repositories on creation

app/agents/git_hub_agent.rb, app/views/resources/_list-item.html.erb, app/workers/resources/request_delete_worker.rb
See individual commits for details.
=> UI tweaks + more resilient handling of resource failures

package.json, yarn.lock
See individual commits for details.
=> Upgrade some frontend deps

.env, app/agents/ecr_agent.rb, app/helpers/resources_helper.rb, app/services/resource_types_service.rb, app/views/application/forms/_json_schema_fields.html.erb, app/workers/resources/base_worker.rb, app/workers/resources/request_create_worker.rb, app/workers/resources/request_delete_worker.rb, config/initializers/agents.rb, config/providers.yml, docker-compose.yml, spec/integration/resources/docker_repos/ecr_docker_repos_integration_spec.rb
- adding the ecr agent provider to the hub
- @note: presently missing the unit tests
=> ECR Agent Provider

docker-compose.yml
Adding docker-compose section for grafana
=> adding hub-grafana-agent to docker-compose

app/helpers/application_helper.rb, app/helpers/sidebar_helper.rb, app/views/application/_sidebar-content.html.erb, app/webpack/stylesheets/_sidebar.scss
This now makes it so all nav items use the `nav_item` or new `nav_list_item` helpers.
=> UI: made the sidebar nav items cleaner and more consistent

app/views/layouts/application.html.erb, app/webpack/stylesheets/application.scss
=> UI: add an icon next to external links that open in a new tab

app/views/application/_sidebar-content.html.erb
- `New space` button --> `New`
- `Admin` --> `Integrations`
=> UI: couple of renames for the sidebar

app/agents/git_hub_agent.rb
Broken in https://github.com/appvia/appvia-hub/commit/32fbc69bfdc03218d8833df1f0e11988029eefb3#diff-3bedcc0ee62e37565625cc97d128d128R42
=> Fix `delete_repository` in the GitHub Agent

docker-compose.yml
- bumping the version of the ecr agent
=> ECR Agent Version

app/agents/git_hub_agent.rb
Closes #68.
This brings the agent in line with all other agents – if the underlying repo already exists then just use that.
=> GitHub Agent: handle existing repos transparently

lib/tasks/hub.rake
E.g.
```shell
EXCLUDE_SPACES="foo-1,bar,another-space" bin/rails hub:danger_zone:clean_hub
```
=> Option to exclude certain spaces in the `clean_hub` task

app/agents/git_hub_agent.rb
Partial fix for #153.
If a repo exists, and it doesn't have a 'master` branch yet, we can't enforce the best practices. This change ensures that the create request still goes through without an error. But more work is needed to figure out the best way of enforcing the best practices later on (when the branch does exist).
=> GitHub Agent: Don't apply best practices if 'master' branch doesn't exist

app/models/resources/code_repo.rb, app/views/resources/_list-item.html.erb, app/workers/resources/request_create_worker.rb, spec/integration/resources/code_repos/git_hub_code_repos_integration_spec.rb, spec/integration/resources/code_repos/git_hub_code_repos_overriden_config_integration_spec.rb
=> Store and display a `enforce_best_practices` flag for GitHub code repos

app/controllers/admin/integrations_controller.rb, app/services/resource_types_service.rb, app/views/admin/integrations/_card.html.erb, app/views/admin/integrations/_group.html.erb, app/views/admin/integrations/index.html.erb, spec/requests/admin/integrations_spec.rb
=> Admin UI: scroll to the relevant integration after creating/updating and unmasking

app/agents/loki_agent.rb
- The grafana URI to loki doesnt encode everything
=> Fixing escape of loki URI to exclude ? = : and ,

app/agents/loki_agent.rb, app/services/agents_service.rb, config/providers.yml, spec/integration/resources/logging_dashboards/loki_logging_dashboards_integration_spec.rb
- Allowing a custom name for Loki data source in grafana
=> Loki data source

.eslintrc, app/controllers/application_controller.rb, app/controllers/resources_controller.rb, app/helpers/application_helper.rb, app/views/application/_autorefresh.html.erb, app/views/layouts/application.html.erb, app/webpack/components/Autorefresh.vue, app/webpack/packs/application.js, package.json, spec/requests/resources_spec.rb, yarn.lock
=> Add autorefresh capability and use this after resource creation and deletion

app/views/application/_autorefresh.html.erb, app/webpack/components/Autorefresh.vue
- Made the background more prominent so it's obvious this is going on
- Added a 'Refresh now' button
- Made the 'Stop' link a button to make more obvious
=> UI: Autorefresh widget tweaks

app/controllers/healthcheck_controller.rb, config/routes.rb, docker-compose.yml, spec/requests/healthcheck_spec.rb
Closes #172
Just returns a `204` for now.
=> Basic `/healthz` endpoint

app/models/integration.rb, spec/models/integration_spec.rb
Updating existing integrations was broken due to a validation check that didn't properly account for existing linked integrations.
=> Fix parent integration validation check

app/helpers/application_helper.rb
=> Set the user email for Crisp chat

app/controllers/teams_controller.rb, app/helpers/teams_helper.rb, app/models/team.rb, app/views/projects/show.html.erb, app/views/teams/_form.html.erb, app/views/teams/edit.html.erb, app/views/teams/index.html.erb, app/views/teams/new.html.erb, app/views/teams/show.html.erb, config/routes.rb, db/migrate/20190805083206_create_teams.rb, db/schema.rb, spec/factories/teams.rb, spec/models/team_spec.rb, spec/requests/teams_spec.rb, spec/routing/teams_routing_spec.rb
Not currently hooked up to users and spaces, nor to the nav UI – this is just the basic CRUD flows and views for Teams.
=> Basic Teams CRUD

Gemfile, Gemfile.lock, app/controllers/team_memberships_controller.rb, app/controllers/users_controller.rb, app/helpers/teams_helper.rb, app/models/team.rb, app/models/team_membership.rb, app/models/user.rb, app/serializers/user_serializer.rb, app/views/projects/show.html.erb, app/views/teams/_people.html.erb, app/views/teams/show.html.erb, app/views/users/index.html.erb, app/webpack/components/AddUserToTeam.vue, app/webpack/components/mixins/csrfTokenMixin.js, app/webpack/packs/application.js, config/routes.rb, db/migrate/20190807093015_create_team_memberships.rb, db/migrate/20190807145541_enable_pg_trgm.rb, db/migrate/20190807145601_add_user_search_index.rb, db/schema.rb, package.json, spec/factories/team_memberships.rb, spec/models/team_membership_spec.rb, spec/models/user_spec.rb, spec/routing/team_memberships_routing_spec.rb, yarn.lock
- Add users to a team (via a user search)
- Remove users from a team
- Make / revoke team admins
NOTE: permissions / access control will be done in a later PR.
---
TODO:
- ~~More specs?~~ - this will come in a later PR when we add permissions / access control.
=> People management for teams

Gemfile, Gemfile.lock, config/cluster_creators.yml
- add support for EKS cluster
- bumping the version of the hub-clusters-creator gem (v0.0.8)
=> EKS Clusters

.env, .env.test
Required if docker updated to > `1.24.1` : see docker-compose issue https://github.com/docker/compose/issues/6511#issuecomment-499862627
=> remove export in .env due to docker-compose update

README.md, bin/preview-entrypoint, docker-compose-app-preview.yml
=> QA or preview current app in docker-compose

app/helpers/activity_helper.rb, app/views/activity/_stream.html.erb, app/views/activity/entries/_project.html.erb, app/views/activity/entries/_resource.html.erb, app/views/activity/entries/_team.html.erb, app/views/activity/entries/_team_membership.html.erb, app/views/activity/entries/_user.html.erb
- Separated out the individual auditable type sections into separate partials
- Added error handling on each individual entry so the whole page doesn't crash if one fails
- Improved the handling of the team membership user for team membership activity entries
=> Refactored and improved activity stream + better team membership user handling

app/helpers/application_helper.rb, app/views/application/_sidebar.html.erb, app/views/projects/_form.html.erb, app/views/projects/show.html.erb, app/views/teams/show.html.erb
See individual commits for details.
=> Various UI tweaks for teams

.rubocop.yml, app/controllers/resources_controller.rb, app/lib/json_schema_helpers.rb
Also, ignore specs for this rule.
=> Rubocop: increase Metrics/CyclomaticComplexity from 7 (default) -> 8

app/services/sync_integration_team_service.rb, app/workers/teams/handle_identity_created_worker.rb, app/workers/teams/handle_identity_deleted_worker.rb, app/workers/teams/handle_integration_teams_update_worker.rb, app/workers/teams/handle_team_created_worker.rb, app/workers/teams/handle_team_deleted_worker.rb, app/workers/teams/handle_team_membership_created_worker.rb, app/workers/teams/handle_team_membership_deleted_worker.rb, spec/integration/teams/git_hub_teams_integration_spec.rb
This ensures that a single failure with an integration or team doesn't prevent others from processing.
=> Catch and log errors during individual processing of items within teams workers

app/controllers/resources_controller.rb
A bug exists which prevents creating a service catalog instance under the following scenario:
* multiple kubernetes cluster integrations and are allocated to the team or open to all teams
* and a service catalog integration is created for each of those kubernetes integrations
This was due to:
* the controller finding multiple service catalog integrations for the team
* the form would render a form for for each integration
* upon submission the values would be taken from the “last” form (which was hidden)
* this resulted in the selected class name not persisting
This has been fixed as follows:
* applying an extra filter the integrations found
* the integration’s parent must match the integration of the parent of the resource that is being created
=> Fixing creating service catalog resource when multiple integration allocations exist

app/views/application/_header.html.erb
=> UI: show hub admin status in header

app/controllers/admin/integrations_controller.rb, spec/requests/admin/integrations_spec.rb
=> Fix case when trying to create a dependent integration without any available parents

app/workers/admin/task_worker.rb
- fixing the reference to the catalog result set
=> Catalog Reference

app/views/application/_clipboard_copy.html.erb, app/views/integrations/_set_up_access.html.erb, app/webpack/packs/application.js, package.json, yarn.lock
* using a read-only input with an inline button and tooltip
* extracted as a partial so it can be re-used elsewhere
* currently done for kubernetes, quay and ECR
Closes https://github.com/appvia/appvia-hub/issues/237
=> Copy to clipboard for access commands

.circleci/config.yml, Dockerfile, app/controllers/version_controller.rb, config/initializers/app_config.rb, config/routes.rb, docker-compose.yml
* set at image build time
* no authentication required to get version endpoint
Related PR for deployment: https://github.com/appvia/kube-appvia-hub/pull/1
=> Setting version and exposing via version endpoint

app/agents/quay_agent.rb, app/services/resource_checks_service.rb, docker-compose.yml
* upgrading the agent to v0.0.7
* using the lazy loading the same as the other checks
99% of this work was done by @danielwhatmuff 👍
=> Adding quay security checks
