appvia/appvia-hub

app/models/resource.rb, spec/support/is_a_resource_examples.rb
Previously, any new resource created would have it's name prefixed with the slug of the project (aka space) that resource was contained. This was intended to isolate resources to avoid name clashes between projects/spaces.
However, given the current open projects/spaces model, this prefixing was unnecessary complexity and inflexibility at this stage. We can always add this back in for closed teams/projects/space if/when we get to that.
=> Remove auto prefixing of resource names

.env, .env.test, Gemfile, Gemfile.lock, app/agents/grafana_agent.rb, app/controllers/projects_controller.rb, app/helpers/application_helper.rb, app/helpers/resources_helper.rb, app/models/resource.rb, app/models/resources/monitoring_dashboard.rb, app/services/resource_provisioning_service.rb, app/services/resource_types_service.rb, app/views/activity/_stream.html.erb, app/views/resources/_list-item.html.erb, app/webpack/stylesheets/application.scss, app/workers/resources/base_worker.rb, app/workers/resources/request_create_worker.rb, app/workers/resources/request_delete_worker.rb, config/initializers/agents.rb, config/providers.yml, db/migrate/20190501141450_add_parent_id_to_resources.rb, db/migrate/20190501143452_create_resource_hierarchies.rb, db/schema.rb, docker-compose.yml, spec/factories/resources.rb, spec/integration/resources/kube_namespaces/kubernetes_kube_namespaces_integration_spec.rb, spec/integration/resources/monitoring_dashboards/grafana_monitoring_dashboards_integration_spec.rb, spec/models/integration_spec.rb, spec/support/mocked_integration_helper.rb, spec/support/resource_integration_specs_examples.rb
Part of #117
Highlights:
- Introduces the concept of "dependent" resources – a resource that is dependent on another.
- In this case, a `MonitoringDashboard` resource (which has been added in this PR) can only exist if it is "attached" to another resource…
- … currently to `KubeNamespace` resources.
- Thus the create and delete workers for `KubeNamespace` make sure to request create / delete of a dependent `MonitoringDashboard` resource.
- And the UI shows these "embedded" within the `KubeNamespace` entry.
---
**TODO:**
=> Grafana monitoring dashboards for Kube namespaces

lib/tasks/hub.rake
Closes #130 
Deletes all resources and projects (aka spaces), together with their associated audits.
Run using:
```shell
bin/rails hub:danger_zone:clean_hub
```
=> Rake task to get the hub to a clean state

app/services/project_resources_bootstrap_service.rb
One will get provisioning _after_ the Kube namespace.
=> Don't provision a separate monitoring dashboard as part of the project resources bootstrap

app/controllers/concerns/authentication.rb
This is to support requirements like #157, where certain auth proxies in front of the hub will pass certain headers for the authed user info.
=> Make auth headers configurable

.env, app/controllers/application_controller.rb, app/controllers/concerns/authentication.rb, app/views/application/_header.html.erb, app/webpack/stylesheets/_variables.scss, config/initializers/authentication.rb
Closes #67
A new config option is now available – `AUTH_LOGOUT_URL` – to specify the logout URL (that needs to be handled by the auth proxy).
Note: this currently doesn't work properly with the local Keycloak Gatekeeper setup – it errors with a `400` error. More investigation is required (which we can do separately).
=> Auth logout

app/models/identity.rb, app/services/git_hub_identity_service.rb, db/migrate/20190704143604_add_access_token_to_identities.rb, db/schema.rb
This is required for [User-to-Server API requests to the GitHub API](https://developer.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps/#user-to-server-requests).
=> Store the user's GitHub access token when they connect their GitHub identity

app/controllers/resources_controller.rb, app/views/resources/_form.html.erb
This now splits the two options in to separate form inputs/values instead of relying on esoteric behaviour of a single overloaded form value.
=> Fix the options select vs custom template_url

app/helpers/application_helper.rb, app/helpers/projects_helper.rb
Closes #189
Until we get to implementing a [proper deletion of spaces](https://github.com/appvia/appvia-hub/issues/98) this UI change disables the delete action when Spaces contain resources, which a useful info message.
=> UI: Disable delete action for Spaces that contain resources

Gemfile, Gemfile.lock, app/controllers/admin/integrations_controller.rb, app/helpers/integrations_helper.rb, app/models/integration.rb, app/models/resource.rb, app/services/dependent_integrations_service.rb, app/services/resource_provisioning_service.rb, app/services/resource_types_service.rb, app/views/admin/integrations/_card.html.erb, app/views/admin/integrations/_form.html.erb, app/workers/resources/request_create_worker.rb, db/migrate/20190717134327_drop_resource_hierarchies.rb, db/migrate/20190717151518_add_parent_id_to_integrations.rb, db/schema.rb, spec/integration/resources/kube_namespaces/kubernetes_kube_namespaces_integration_spec.rb, spec/integration/resources/logging_dashboards/loki_logging_dashboards_integration_spec.rb, spec/integration/resources/monitoring_dashboards/grafana_monitoring_dashboards_integration_spec.rb, spec/models/integration_spec.rb, spec/support/mocked_integration_helper.rb, spec/support/resource_integration_specs_examples.rb
This fixes the issue where `grafana` and `loki` integrations were previously not tied to a specific `kubernetes` integration, and thus multiple `kubernetes` integrations would not get dependent resources as expected.
Now, certain integrations – as marked within the relevant Resource Type – _depend on_ parent integration(s). Child integrations can have multiple parents (which allows for reuse of a single child integration for multiple parents – e.g. a single Grafana integration for multiple Kubernetes Clusters).
When creating (or editing) integrations that require a parent, the form will provide the relevant parent options and allow multiple selection. However the following validations are in place at the model level (specifically for integrations that require a parent):
- At least one …
=> Support for dependent/linked integrations

app/controllers/admin/integrations_controller.rb, app/helpers/integrations_helper.rb, app/views/admin/integrations/_card.html.erb, config/routes.rb, spec/requests/admin/integrations_spec.rb, spec/routing/admin/integrations_routing_spec.rb
Works the same way as the space (aka project) delete, except only available to hub admins.
=> Admin: Ability to delete integrations that don't have any resources

app/views/resources/_form.html.erb
We don't use `<fieldset>` anywhere – instead we wrap sub forms in cards, so this change brings the resource form more in line with the other forms.
=> UI: Fix resource form styling to be more consistent

app/services/activity_service.rb
Only pick the auditable types we know we show in the activity stream.
NOTE: this doesn't fully solve the issue of there being some fetched audits that still don't get shown in the UI – e.g. we don't show the audits for the `Resource` `create` in the activity streams (as we rely on the `request_create` instead). However, it's much harder to formulate a query to exclude just this particular case, so the net effect is we fetch up to 20 audits but may not show 20 activity stream items in the UI.
=> Restrict which audits we fetch for the activity stream

.circleci/config.yml
Steps need tags to be _whitelisted_ in order to work.
=> Fix CircleCI tags build

Gemfile, Gemfile.lock, app/controllers/projects_controller.rb, app/helpers/projects_helper.rb, app/helpers/sidebar_helper.rb, app/helpers/teams_helper.rb, app/models/project.rb, app/models/team.rb, app/views/activity/_stream.html.erb, app/views/application/_sidebar.html.erb, app/views/projects/_form.html.erb, app/views/projects/edit.html.erb, app/views/projects/index.html.erb, app/views/projects/new.html.erb, app/views/projects/show.html.erb, app/views/teams/_projects.html.erb, app/views/teams/index.html.erb, app/views/teams/show.html.erb, db/migrate/20190805135446_add_team_id_to_project.rb, db/schema.rb, spec/factories/projects.rb, spec/models/project_spec.rb, spec/requests/projects_spec.rb, spec/requests/resources_spec.rb
With this change, all spaces MUST be assigned to a team.
NOTE: for now, the sidebar contains the full list of both teams and spaces. This will change as we add users to teams and introduce permissions and access restrictions (e.g. this may change to show only the current user's teams and spaces).
=> Scope spaces to teams

app/controllers/teams_controller.rb, app/models/user.rb, app/views/application/_sidebar.html.erb
Now separated into the following sections:
- a tree of the current user's teams and spaces within those teams
- a link to "All Teams" with a "New" button
- a link to "All Spaces" with a "New" button
---
As part of this, also needed:
Make the creator of a team an admin of the team (the first commit in this PR)
=> Redo the teams and spaces links in the sidebar

Gemfile, Gemfile.lock, app/controllers/home_controller.rb, app/controllers/teams_controller.rb, app/models/team_membership.rb, app/services/activity_service.rb, app/views/activity/_stream.html.erb, app/views/projects/show.html.erb, app/views/teams/show.html.erb, db/migrate/20190807093015_create_team_memberships.rb, db/schema.rb, spec/requests/home_spec.rb, spec/requests/projects_spec.rb, spec/requests/teams_spec.rb
- New activity stream on the team show page for team related activity (excluding resources - for this you need to drill down into individual spaces).
- Lock down the _home_ activity stream to current user's teams and spaces only.
Also as part of this:
- I've fixed the issue where filtering of audits would result in smaller or empty streams than expected – now we:
1. Have a "fill" mechanism keeps building the list (within a certain time window) until either no more are found in the audits, or the page size is met.
2. Query very specifically for only the auditable types and actions that are supported in the UI.
- I had to redo the `team_memberships` db table schema as it previously didn't have a primary key, which is now needed for Audits to work properly.
=> Revamped activity streams for new Teams feature

app/controllers/me/access_controller.rb, app/controllers/me/identity_flows_controller.rb, app/models/ability.rb, app/models/identity.rb, app/services/team_integrations_service.rb, spec/integration/resources/code_repos/git_hub_code_repos_using_template_spec.rb, spec/models/identity_spec.rb, spec/requests/me/identities_spec.rb, spec/requests/me/identity_flows_spec.rb, spec/services/team_integrations_service_spec.rb
Only allow connecting an identity if the user has access to the integration tied to that identity.
=> Lock down the connecting of an identity

app/views/application/_header.html.erb, docker-compose.yml
* use latest version of `mock-oidc-user-server` - `v0.0.4`
* specify logout redirect URI
* disable turbolinks on logout link
=> Prevent logout from throwing an error when running locally

app/helpers/teams_helper.rb, app/views/teams/index.html.erb, app/views/teams/show.html.erb
… until we do it properly (ref: https://github.com/appvia/appvia-hub/issues/98).
Note: this still leaves the backend for delete in place, which will fail if you try and delete a team with any spaces or allocations.
=> UI: Remove team delete option for now

app/services/sync_integration_team_service.rb, spec/integration/resources/code_repos/git_hub_code_repos_integration_spec.rb, spec/integration/resources/code_repos/git_hub_code_repos_overridden_config_integration_spec.rb, spec/integration/resources/code_repos/git_hub_code_repos_using_template_spec.rb, spec/integration/teams/git_hub_teams_integration_spec.rb
This is now `hub-{team.slug}`, which should be make it more conformant in different integrations (like Kubernetes).
=> Change the team name used externally in integrations to be more conformant

app/models/concerns/slugged_attribute.rb, spec/support/slugged_attribute_examples.rb
Fixes #267
This is because Kubernetes doesn't allow underscores in names.
=> Don't allow underscores in slugs

app/views/resources/_form.html.erb, app/webpack/controllers/resource_form_controller.js
* server renders resource form per integration and JS hides the non-selected one using `display: none` on the container
* elements in a container with `display: none` (or with `display: none` set directly) are still submitted by the browser
* this will cause issues due to duplicate names being used and wrong values being received on the server
* fix this by setting the `disabled` attribute for all the resource form elements as well as hiding the container
* maintain the disabled state rendered by the server, by JS setting the disabled value as `disabled_form`, then only removed `disabled` attribute if value is set to this
=> Fix integration switching resource form behaviour

app/helpers/sidebar_helper.rb, app/views/application/_sidebar.html.erb
Hub admins can still create new spaces even if they aren't a part of team yet (as long as there are teams present).
=> UI: fix new space button

app/helpers/json_schema_helper.rb, app/lib/json_schema_helpers.rb, app/views/application/forms/json_schema/_field.html.erb, app/views/application/forms/json_schema/_fields.html.erb, app/views/application/forms/json_schema/_fields_additional_properties.html.erb, app/views/application/forms/json_schema/_fields_array_item.html.erb, app/views/application/forms/json_schema/_fields_nested_field.html.erb, app/views/application/forms/json_schema/_fields_nested_object.html.erb, app/views/integration_overrides/show.html.erb, app/views/resources/_form.html.erb, app/views/resources/_service_catalog_instance_list.html.erb, app/webpack/controllers/form_nested_list_controller.js, app/workers/resources/request_create_worker.rb, spec/lib/json_schema_helpers_spec.rb
**Fixes and enhancements to JSON schema templates**
* fixing tooltips so they are generated when JS adds new form elements
* fixing `required` attribute on boolean type select element
* adding an extra div around nested object items in order to keep the title in the deleted div
* supporting `oneOf` when used to specify a set of allowed strings using `enum` or just `title`
* supporting string array
* load bootstrap-select when adding nested elements
* support array of strings using `oneOf` - render a multi-select box
* setting `include_blank` in relation to `required`, if field is required `include_blank` must be set
**Supporting use of type string additionalProperties in JSON schema**
* set out as repeating key/value pairs
* processed on the server into properties on the parent
* also …
=> Azure service broker

app/controllers/resources_controller.rb, app/helpers/json_schema_helper.rb, app/lib/json_schema_helpers.rb, app/models/concerns/encrypted_config_hash_attribute.rb, app/models/concerns/json_schema_validation.rb, app/models/integration.rb, app/models/integration_override.rb, app/models/resources/service_catalog_instance.rb, app/services/service_catalog_service.rb, app/views/application/forms/json_schema/_field.html.erb, app/views/resources/_form.html.erb, spec/lib/json_schema_helpers_spec.rb, spec/models/integration_spec.rb, spec/services/service_catalog_service_spec.rb, spec/support/mocked_integration_helper.rb
**JSON schema form generator enum enhancement**
* render a select box when `enum` is found for type `string` or `integer`
* this an alternative way to specify a value must be from a predefined list of values
**Service catalog plan JSON schema validation**
* reusing the schema validation used by the integrations
* refactoring it out for use elsewhere
* maintaining encrypted config hash attribute concern for that purpose only
* permit any parameters under service catalog plan parameters
* enhance `JsonSchemaHelpers.ensure_data_types` to only convert empty strings to `nil` for required properties
* adding new method in `JsonSchemaHelpers` to prepare data for validation
* amending `service_catalog_service` to be able to get a parsed JSON schema
* store the schema on the service catalog …
=> Service catalog JSON schema validation

app/controllers/me/access_controller.rb, app/views/me/access/_entry.html.erb, app/views/me/access/_identity.html.erb, app/views/me/access/show.html.erb
Closes #296
"Unused identities" = identities previously connected in the hub but now unneeded, due to access to the integration being removed from team(s).
=> Access page now shows unused identities

app/webpack/packs/application.js
* initialise on the `turbolinks:load` event instead of DOM ready
=> Fixing clipboard to play nicely with turbo links

.gitignore, Dockerfile, app/controllers/version_controller.rb, config/initializers/app_config.rb, config/routes.rb
* having a `VERSION` env var set interferes with the DB migration
* this is still accessible via the `/version` endpoint
=> Changing version to be written to a file in public directory

app/views/resources/_card.html.erb
Very minor CSS change, for discussion - take it or leave it, I don't mind.
BEFORE:
AFTER:
=> Removing padding and margins around each status bar

app/models/project.rb, app/services/teams_service.rb, lib/tasks/hub.rake, spec/rails_helper.rb, spec/tasks/hub/clean_hub_spec.rb
Closes #298 
Highlights:
- Now deletes and cleans up teams.
- New `EXCLUDE_TEAMS` env var to exclude certain teams (works in conjunction with the existing `EXCLUDE_SPACES` env var).
- Projects (aka spaces) are now deleted using the appropriate service object, so that things like robot tokens are cleaned up.
=> Support teams deletion in the `clean_hub` script (#298)
